// pageRequest: {
//     page: 1,
//     size: 10,
//     type: '',
//     sort: 'hireId',
//     ffrom: 0,
//     fto: 0,
//     conKeyword: '',
//     castKeyword: '',
//     gfrom: 0,
//     gto: 0,
//     tkeyword: 0,
//     pkeyword: 0,
// },
// pageResult: {
//     pageList: [],
//     dtoList: [],
//     page: 1,
//     size: 10,
//     totalPage: 0,
//     start: 0,
//     end: 0,
//     prev: false,
//     next: false,
//     totalElement: 0,
// },
